version: 0.2

phases:
  install:
    commands:
      - echo Installing OpenJDK 11...
      - apt-get update
      - apt-get install -y openjdk-11-jdk

      - echo Installing Maven 3.3.1...
      - curl -sL https://archive.apache.org/dist/maven/maven-3/3.3.1/binaries/apache-maven-3.3.1-bin.tar.gz | tar xz -C /opt
      - export MAVEN_HOME=/opt/apache-maven-3.3.1
      - export PATH=$MAVEN_HOME/bin:$PATH

      - echo "Maven version: $(mvn --version)"

  pre_build:
    commands:
      - echo Pre-build phase: Running Maven Clean
      - mvn clean

  build:
    commands:
      - echo Building the project...
      - mvn package

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - target/*.war
  discard-paths: yes
