version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y openjdk-11-jdk
      - curl -sL https://archive.apache.org/dist/maven/maven-3/3.3.1/binaries/apache-maven-3.3.1-bin.tar.gz | tar xz -C /opt
      - cd /
      - mv /opt/apache-maven-3.3.1 /usr/local/maven
      - echo "Maven version: $(./usr/local/maven/bin/mvn --version)"

  pre_build:
    commands:
      - ./usr/local/maven/bin/mvn clean

  build:
    commands:
      - ./usr/local/maven/bin/mvn package

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - target/*.war
  discard-paths: yes
